let object = {
    "id": 941930004,
    "node_id": "R_kgDOOCS2FA",
    "name": "1cs-ai-fundamentals-assignments",
    "full_name": "raufzer/1cs-ai-fundamentals-assignments",
    "private": false,
    "owner": {
      "login": "raufzer",
      "id": 112574242,
      "node_id": "U_kgDOBrW_Ig",
      "avatar_url": "https://avatars.githubusercontent.com/u/112574242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raufzer",
      "html_url": "https://github.com/raufzer",
      "followers_url": "https://api.github.com/users/raufzer/followers",
      "following_url": "https://api.github.com/users/raufzer/following{/other_user}",
      "gists_url": "https://api.github.com/users/raufzer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raufzer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raufzer/subscriptions",
      "organizations_url": "https://api.github.com/users/raufzer/orgs",
      "repos_url": "https://api.github.com/users/raufzer/repos",
      "events_url": "https://api.github.com/users/raufzer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raufzer/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/raufzer/1cs-ai-fundamentals-assignments",
    "description": "Assignments for the AI module (1CS). Covers logic, search algorithms , CSPs, expert systems, and more.",
    "fork": false,
    "url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments",
    "forks_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/forks",
    "keys_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/teams",
    "hooks_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/hooks",
    "issue_events_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/issues/events{/number}",
    "events_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/events",
    "assignees_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/assignees{/user}",
    "branches_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/branches{/branch}",
    "tags_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/tags",
    "blobs_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/languages",
    "stargazers_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/stargazers",
    "contributors_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/contributors",
    "subscribers_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/subscribers",
    "subscription_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/subscription",
    "commits_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/contents/{+path}",
    "compare_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/merges",
    "archive_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/downloads",
    "issues_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/issues{/number}",
    "pulls_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/labels{/name}",
    "releases_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/releases{/id}",
    "deployments_url": "https://api.github.com/repos/raufzer/1cs-ai-fundamentals-assignments/deployments",
    "created_at": "2025-03-03T09:42:36Z",
    "updated_at": "2025-06-02T22:14:00Z",
    "pushed_at": "2025-04-11T09:34:27Z",
    "git_url": "git://github.com/raufzer/1cs-ai-fundamentals-assignments.git",
    "ssh_url": "git@github.com:raufzer/1cs-ai-fundamentals-assignments.git",
    "clone_url": "https://github.com/raufzer/1cs-ai-fundamentals-assignments.git",
    "svn_url": "https://github.com/raufzer/1cs-ai-fundamentals-assignments",
    "homepage": "",
    "size": 7681,
    "stargazers_count": 11,
    "watchers_count": 11,
    "language": "Jupyter Notebook",
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": true,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "folium",
      "jupyter-notebook",
      "matplotlib",
      "numpy",
      "pandas",
      "python",
      "scipy"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 11,
    "default_branch": "main"
  }